import './bootstrap';
import './user-menu';
import './login';
import './catalogo-bienes';
import './estaciones';
import './toma-inventario';
import './movimientos';
import './mantenimientos';
import './reportes';
